version: '3.7'

services:
  app:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-maz-converter
    depends_on: [db]
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    configs:
      - source: sva-bad-belzig-maz-converter-database-yml
        target: /app/config/database.yml
      - source: sva-bad-belzig-maz-converter-unicorn-rb
        target: /app/config/unicorn.rb
      - source: sva-bad-belzig-maz-converter-master-key
        target: /app/config/master.key
      - source: sva-bad-belzig-maz-converter-production-key
        target: /app/config/credentials/production.key
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - unicorn:/unicorn
      - assets:/assets
    deploy:
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx
    depends_on: [app]
    networks: [default, public]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - unicorn:/unicorn
      - assets:/public
    labels:
      - traefik.docker.network=public
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_USER: smart
      POSTGRES_PASSWORT: smart
      POSTGRES_DB: smart
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - db:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  db:
  unicorn:
  assets:

configs:
  sva-bad-belzig-maz-converter-nginx-conf:
    external: true
  sva-bad-belzig-maz-converter-database-yml:
    external: true
  sva-bad-belzig-maz-converter-unicorn-rb:
    external: true
  sva-bad-belzig-maz-converter-master-key:
    external: true
  sva-bad-belzig-maz-converter-production-key:
    external: true

networks:
  public:
    external: true
