version: '3.7'

services:
  app:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-maz-converter:bad-belzig
    networks:
      - default
      - public
      - logs
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    volumes:
      - /etc/localtime:/etc/localtime:ro

  nginx:
    configs:
      - source: sva-bad-belzig-maz-converter-nginx-conf
        target: /etc/nginx/conf.d/default.conf
    deploy:
      labels:
        traefik.docker.network: public
        traefik.enable: "true"
        traefik.frontend.passHostHeader: "true"
        traefik.frontend.redirect.entryPoint: https
        traefik.frontend.rule: Host:maz.bad-belzig.smart-village.app,maz.bad-belzig.smart-village-app.tpwd.de
        traefik.port: '80'

  db:
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      adminer:
        aliases:
          - mysql-bad-belzig-maz-importer

networks:
  adminer:
    external: true
  logs:
    external: true
  public:
    external: true
